# Generated by Django 5.1.7 on 2025-04-24 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='src',
            new_name='image',
        ),
    ]
