# Generated by Django 5.1.7 on 2025-04-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
