# Generated by Django 5.1.7 on 2025-04-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_content_status_alter_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('vid', 'Video'), ('aud', 'Audio'), ('img', 'Imagen')], max_length=10),
        ),
    ]
