# Generated by Django 5.1.7 on 2025-04-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Imagen', 'Imagen')], max_length=10),
        ),
    ]
