# Generated by Django 5.1.7 on 2025-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
